export const quotes = [
  "Kindness builds real strength.",
  "Brave is not loud — it’s honest.",
  "Asking for help is a smart move!",
  "Listening shows true respect.",
  "It’s okay to feel everything.",
  "Small steps make big change!",
  "Your words shape the moment.",
  "Courage is doing it anyway.",
  "Mistakes are part of learning.",
  "Confidence grows with effort!",
  "A calm mind speaks the clearest.",
  "You lead best when you care.",
  "Being real is always enough.",
  "Emotions aren’t bad — they’re clues.",
  "Practice makes progress!",
  "You can’t grow without trying.",
  "Patience is powerful!",
  "Helping others helps you too.",
  "Respect starts with listening.",
  "You’re learning more than you think!",
];